<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="NodaTime" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Vandox.Core.Tests" />
    <InternalsVisibleTo Include="Vandox.Import" />
  </ItemGroup>

</Project>
